In [1]:
import numpy as np

In [17]:
print("version       :",np.__version__)
print(np.show_config())

version       : 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Jit/anaconda3/Library/include
    lib directory: C:/Users/Jit/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: window

In [4]:
null_vector = np.zeros(20)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1
print(null_vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
print("reverse of vector is :", vector[::-1])

reverse of vector is : [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [20]:
matrix = np.arange(2, 14).reshape(4,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [21]:
A = [1,2,0,0,4,0]
np.nonzero(A)

(array([0, 1, 4], dtype=int64),)

In [22]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
matrix = np.random.rand(3,3,3)
print(matrix)

[[[0.9857584  0.30653089 0.45072827]
  [0.93847709 0.29259821 0.36236676]
  [0.36310691 0.76989953 0.41539835]]

 [[0.37479964 0.05776737 0.50650438]
  [0.73867102 0.47482396 0.60920713]
  [0.85765552 0.61462685 0.1364037 ]]

 [[0.74427402 0.2590225  0.10690915]
  [0.02169618 0.1669685  0.65855525]
  [0.45076693 0.93408991 0.23899232]]]


In [24]:
matrix =  np.random.rand(10, 10)
print("max value:",np.max(matrix))
print("min value:",np.min(matrix))

max value: 0.9888220326386932
min value: 0.009427170836306509


In [25]:
vector = np.random.rand(30)
print(vector)

[0.59829926 0.55795473 0.31540326 0.28241693 0.43969241 0.90541793
 0.65388554 0.95374642 0.90438548 0.89386749 0.12026493 0.58545845
 0.65194164 0.09754336 0.29567061 0.82140625 0.19052262 0.36589829
 0.67694265 0.64188398 0.82653756 0.32819755 0.58004048 0.05551438
 0.70064126 0.7970646  0.82381266 0.99644044 0.04994075 0.44714905]


In [26]:
matrix = np.zeros((5, 5))
print("initial matrix:\n",matrix)
matrix[0,:]=1
matrix[:,0]=1
matrix[:,-1]=1
matrix[-1,:]=1
print("final matrix:\n",matrix)

initial matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
final matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
matrix = np.zeros((8,8))
matrix[0::2,1::2]=1       #(0th to all row,1st to all column)  even row odd column
matrix[1::2,0::2]=1       #(1st to all row,0th to all column)  odd row even column
print("Checkerboard Pattern:\n",matrix)

Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [28]:
matrix1 = np.random.rand(5,3)
matrix2 = np.random.rand(3,2)
print("multiplication:(using @ symbol):\n",matrix1 @ matrix2)
print("multiplication:(using dot):\n",np.dot(matrix1,matrix2))

multiplication:(using @ symbol):
 [[0.69997115 1.11581542]
 [1.04545732 0.82392546]
 [0.59426673 0.54634756]
 [0.74452727 1.12016085]
 [0.5578176  0.08586917]]
multiplication:(using dot):
 [[0.69997115 1.11581542]
 [1.04545732 0.82392546]
 [0.59426673 0.54634756]
 [0.74452727 1.12016085]
 [0.5578176  0.08586917]]


In [29]:
import numpy as np
array= np.random.uniform(0,10,size=10)
array[(array >= 3) & (array <= 8)] *= -1
print(array)

[ 8.18130295  2.00426275 -3.49847711  2.22178331 -7.83939615 -6.76449585
  0.64434795 -7.85588421 -3.17169243  1.21396629]


In [30]:
random_vector = np.random.randint(1,100,size=10)

print("sorted list:(using sorted keyword)",sorted(random_vector))
random_vector.sort()
print("sorted list:(using sort keyword)",random_vector)

sorted list:(using sorted keyword) [4, 15, 50, 63, 67, 78, 86, 94, 95, 99]
sorted list:(using sort keyword) [ 4 15 50 63 67 78 86 94 95 99]


In [31]:
random_vector = np.random.randint(1,50,size=10)
print("original array :",random_vector)
max = np.argmax(random_vector)
random_vector[max]=0
print("array after replacing max no:",random_vector)

original array : [ 2 18 33 40 13 31 28 46  6 30]
array after replacing max no: [ 2 18 33 40 13 31 28  0  6 30]


**Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.**

In [57]:
#Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.
mobile_prices = [ 6999, 7500, 11999, 27899, 14999, 9999]

# a. Create a 1d-array of mobile phones prices
mp_array = np.array(mobile_prices)
print("mobile_price array:",mp_array)


#b. Convert this array to float type
float_array = mp_array.astype(float)
print("floated array :",float_array)


#c. Append a new mobile having price of 13999 Rs. to this array
print("appended array:",np.append(float_array,13999))


#d. Reverse this array of mobile phones prices
mobile_prices.reverse()
print("reversed array of mobile_prices:",mobile_prices)


#e. Apply GST of 18% on mobile phones prices and update this array.
for i in range(len(mobile_prices)):
  mobile_prices[i]*=1.18

print("after applying GST :",mobile_prices)

#f. Sort the array in descending order of price 
mobile_prices.sort(reverse=True)
print("mobile prices in descending order :",mobile_prices)\

#g. What is the average mobile phone price 
total_price = sum(mobile_prices)
phones = len(mobile_prices)
avg_price = total_price/phones
print("average price:",avg_price)


#h. What is the difference b/w maximum and minimum price
maximum_price = np.max(mobile_prices)
minimum_price = np.min(mobile_prices)
price_difference = maximum_price - minimum_price
print("Difference between maximum and minimum price:", price_difference)

mobile_price array: [ 6999  7500 11999 27899 14999  9999]
floated array : [ 6999.  7500. 11999. 27899. 14999.  9999.]
appended array: [ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]
reversed array of mobile_prices: [9999, 14999, 27899, 11999, 7500, 6999]
after applying GST : [11798.82, 17698.82, 32920.82, 14158.82, 8850.0, 8258.82]
mobile prices in descending order : [32920.82, 17698.82, 14158.82, 11798.82, 8850.0, 8258.82]
average price: 15614.35
Difference between maximum and minimum price: 24662.0
