In [4]:
import numpy as np

print(np.__version__)

1.24.3


In [6]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\in

In [10]:
null_vector = np.zeros(20)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
reverse_vector = np.flip(vector)
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
matrix = np.arange(2,14).reshape(4,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [20]:
A = [1, 2, 0, 0, 4, 0]
matrix = np.nonzero(A)
print("indexes of non zero elements:")
print(matrix)

indexes of non zero elements:
(array([0, 1, 4], dtype=int64),)


In [22]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
matrix = np.random.rand(3,3,3)
print(matrix)

[[[0.79845465 0.82419677 0.71222278]
  [0.41784528 0.9120322  0.83722129]
  [0.25230914 0.73356234 0.51098608]]

 [[0.86512542 0.81495642 0.23639682]
  [0.28408162 0.2969839  0.23293708]
  [0.31390152 0.2437732  0.30546243]]

 [[0.36556627 0.00207626 0.02328694]
  [0.63648712 0.60537198 0.16776062]
  [0.64244213 0.45037163 0.14438364]]]


In [26]:
matrix = np.random.rand(10,10)
print(matrix)
print("min", np.min(matrix))
print("max", np.max(matrix))

[[0.97244801 0.15449449 0.11703968 0.07975185 0.46137657 0.63998831
  0.1219118  0.99497058 0.10687897 0.42296746]
 [0.57445754 0.07797743 0.60081199 0.26264089 0.08195653 0.11201813
  0.63426067 0.55925217 0.97139927 0.50249104]
 [0.24794205 0.05931695 0.95241623 0.17713039 0.45270004 0.87135874
  0.3302835  0.9088248  0.81134438 0.36899709]
 [0.4739832  0.99556198 0.11057475 0.04639178 0.50306648 0.28567393
  0.43713216 0.31558086 0.9934695  0.59384381]
 [0.74881418 0.89400423 0.49862967 0.33426961 0.5337658  0.38029764
  0.93056968 0.21441948 0.32128226 0.98423126]
 [0.89418298 0.34786866 0.84058294 0.60346121 0.0258072  0.13244273
  0.21824246 0.73492621 0.34596458 0.87162324]
 [0.11437381 0.42590087 0.91640708 0.35387771 0.18686053 0.42193328
  0.57980953 0.6351519  0.07782947 0.45038385]
 [0.45030802 0.64383621 0.07233141 0.10185173 0.72114469 0.33467558
  0.82352949 0.13652462 0.21995001 0.00655892]
 [0.20135953 0.34182977 0.13518474 0.9724724  0.4011812  0.45278913
  0.06739231

In [30]:
vector = np.random.rand(30)
print(vector)
print("mean :", np.mean(vector))

[0.40514861 0.47907612 0.11065241 0.81517577 0.42388012 0.55573765
 0.68236238 0.82078718 0.37471022 0.22868731 0.12281455 0.87864895
 0.13979084 0.84876234 0.91627633 0.8052929  0.53258221 0.62646406
 0.51999982 0.03404932 0.65383191 0.07426166 0.83021456 0.04868338
 0.75736079 0.83542709 0.1610721  0.81139177 0.65236918 0.20088499]
mean : 0.5115465503433343


In [34]:
matrix = np.zeros((5,5), dtype=int)
matrix[0,:]=1
matrix[:,0]=1
matrix[-1,:]=1
matrix[:,-1]=1
print("border elements are 1's and inner elements are 0's:\n",matrix)

border elements are 1's and inner elements are 0's:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [36]:
matrix = np.zeros((5,5))
matrix[::2,::2]=0
matrix[1::2,1::2]=0
matrix[::2,1::2]=1
matrix[1::2,::2]=1
print("checkerboard pattern\n",matrix)

checkerboard pattern
 [[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [48]:
matrix1 = np.random.randint(1,10,size=(5,3))
matrix2 = np.random.randint(1,10,size=(3,2))
mul = np.dot(matrix1,matrix2)
print(matrix1)
print(matrix2)
print("multiplication:\n",mul)

print("mul:\n",matrix1 @ matrix2)   

[[8 3 9]
 [4 3 4]
 [1 9 7]
 [2 1 1]
 [8 1 2]]
[[1 4]
 [9 3]
 [9 9]]
multiplication:
 [[116 122]
 [ 67  61]
 [145  94]
 [ 20  20]
 [ 35  53]]
mul:
 [[116 122]
 [ 67  61]
 [145  94]
 [ 20  20]
 [ 35  53]]


In [52]:
A = [1,3,5,2,7,9,8,6]
array = A[(A>3) & (A<8)] 
array *= -1
print(array)

TypeError: '>' not supported between instances of 'list' and 'int'